---

- name: Load default options
  include_vars: 'default.yml'

- name: Combine options
  set_fact:
    vnstat_config_options: '{{ vnstat_default_config_options|combine(vnstat_config_options) }}'

- name: Install vnstat
  package: name=vnstat state=present

- name: Create vnstat database directory
  file:
    path: '{{ vnstat_config_options["DatabaseDir"] }}'
    owner: '{{ vnstat_user }}'
    group: '{{ vnstat_group }}'
    state: directory

- name: Configure vnstat
  template:
    src: config.j2
    dest: '{{ vnstat_config_file }}'
  notify: [ 'Restart vnstat' ]

- name: Initiate vnstat interfaces databases
  command: vnstat --update --iface '{{ item | quote }}'
  args:
    creates: '{{ vnstat_config_options["DatabaseDir"] }}/{{ item }}'
  become_user: '{{ vnstat_user }}'
  with_flattened:
    - '{{ vnstat_interfaces }}'
